application:
  tickrate: 1000000 # microseconds

endpoints:
  - name: reactfinnland
    default: true
    url: "https://api.react-finland.fi/graphql"
    link: "https://api.react-finland.fi/graphql"

themes:
  - name: default
    default: true
    path: theme.ini
