[package]
name = "graphqshell"
version = "0.1.0"
authors = ["certainty <david.krentzlin@gmail.com>"]
edition = "2018"

[lib]
name="graphqshell"
path="src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tui = "0.12.0"
termion = "1.5.5"
linefeed = "0.6.0"
url = "2.1.1"
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "3.0.0-beta.2"
rayon = "1.5.0"
crossbeam-channel = "0.5"
tokio = { version ="0.3.2", features=["full"] }
anyhow = "1.0"
scopeguard = "1.1"
backtrace = "0.3"
thiserror = "1.0"

[dev-dependencies]
mockito = "0.27.0"

