name:                graphqshell
version:             0.1.0.0
github:              "certainty/graphqshell"
license:             BSD3
author:              "certainty"
maintainer:          "david.krentzlin@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/certainty/graphqshell#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - NoImplicitPrelude
  - ConstraintKinds
  - DeriveGeneric
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - ViewPatterns
  - ApplicativeDo
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies

dependencies:
  - base >= 4.7 && < 5
  - relude
  - safe-exceptions
  - bytestring
  - text

library:
  source-dirs: src
  ld-options: 
    - -pthread
  dependencies:
    - brick 
    - vty 
    - async 
    - raw-strings-qq
    - aeson
    - exceptions
    - safe-exceptions
    - either
    - unordered-containers
    - fuzzyset


executables:
  graphqshell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ld-options: 
    - -pthread
    dependencies:
    - graphqshell

  demo_server:
    main: Main.hs
    source-dirs: demo_server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - morpheus-graphql
      - scotty
 

benchmarks:
  graphshell-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphqshell
    - gauge

tests:
  graphqshell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog
    - tasty 
    - tasty-hedgehog
    - tasty-discover 
    - tasty-hspec 
    - graphqshell
    - raw-strings-qq
