version: "3.8"
services:
  tui:
    image: graphqshell_demo
    environment:
      GQL_SERVER_PORT: 5000
    tty: true 
    stdin_open: true
    command: ["/bin/bash", "--init-file", "./entrypoint.sh"]
    links:
      - demo_server
    environment:
      GRAPHQL_API: "http://demo_server:5000/graphql"
  
  demo_server:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    image: graphqshell_demo
    ports:
      - "5000:5000"
    environment:
      GQL_SERVER_PORT: 5000
    command: ["stack", "exec", "demo_server"]
  
