application:
  tickrate: 200 # milliseconds

endpoints:
  - name: example 
    default: true
    url: "https://api.react-finland.fi/graphql"
    link: "https://api.react-finland.fi/graphql"
  - name: weather
    default: false
    url: "https://graphql-weather-api.herokuapp.com/"
    link: "https://graphql-weather-api.herokuapp.com" 
    http:
      custom-headers:
        - name: "TEST_HEADER"
          value: "TEST_HEADER_VALUE"
