name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Stack
      uses: mstksg/setup-stack@v2

    - name: Install dependencies
      run:  stack --no-terminal build --bench --only-dependencies
    - name: Build
      run:  stack --no-terminal build --bench --no-run-benchmarks --haddock --no-haddock-deps
    - name: Run tests
      run: stack --no-terminal test
